Fixing a fatal error on upload page:
Fatal error: Call to a member function isAllowed() on a non-object in /home/rotemliss/Server/wiki/source/trunk/phase3/includes/specials/SpecialUpload.php on line 125

The old code (introduced in r40190) used a $this->mUpload object, which does not exist on GET requests to Special:Upload. The new code uses direct User::isAllowed check in such cases.

svn path=/trunk/phase3/; revision=40215